version: 1
name: marvcode_blog
scripts:
  build:
    - pip install -r requirements.txt
  start:
    - python manage.py migrate
    - python manage.py collectstatic --noinput
    - python manage.py runserver 0.0.0.0:$PORT
services:
  - type: web
    name: marvcode_blog
    buildCommand: python -m pip install -r requirements.txt
    startCommand: python manage.py runserver 0.0.0.0:$PORT
    env: python=3.10.4
  - type: mysql
    name: marvcode_blog_database
databases:
  - name: marvcode_blog_database
    type: mysql

