# Generated by Django 4.0.4 on 2023-08-28 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BootStrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=300)),
                ('link_two', models.CharField(max_length=300)),
                ('link_three', models.CharField(max_length=300)),
                ('link_four', models.CharField(max_length=300)),
                ('link_five', models.CharField(max_length=300)),
                ('link_six', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'BootStrap',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Css',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=300)),
                ('link_two', models.CharField(max_length=300)),
                ('link_three', models.CharField(max_length=300)),
                ('link_four', models.CharField(max_length=300)),
                ('link_five', models.CharField(max_length=300)),
                ('link_six', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Css',
            },
        ),
        migrations.CreateModel(
            name='Django',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=300)),
                ('link_two', models.CharField(max_length=300)),
                ('link_three', models.CharField(max_length=300)),
                ('link_four', models.CharField(max_length=300)),
                ('link_five', models.CharField(max_length=300)),
                ('link_six', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Django',
            },
        ),
        migrations.CreateModel(
            name='JavaScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=300)),
                ('link_two', models.CharField(max_length=300)),
                ('link_three', models.CharField(max_length=300)),
                ('link_four', models.CharField(max_length=300)),
                ('link_five', models.CharField(max_length=300)),
                ('link_six', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'JavaScript',
            },
        ),
        migrations.CreateModel(
            name='ML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=300)),
                ('link_two', models.CharField(max_length=300)),
                ('link_three', models.CharField(max_length=300)),
                ('link_four', models.CharField(max_length=300)),
                ('link_five', models.CharField(max_length=300)),
                ('link_six', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'ML',
            },
        ),
        migrations.CreateModel(
            name='MySQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=300)),
                ('link_two', models.CharField(max_length=300)),
                ('link_three', models.CharField(max_length=300)),
                ('link_four', models.CharField(max_length=300)),
                ('link_five', models.CharField(max_length=300)),
                ('link_six', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'MySQL',
            },
        ),
        migrations.CreateModel(
            name='Python',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=300)),
                ('link_two', models.CharField(max_length=300)),
                ('link_three', models.CharField(max_length=300)),
                ('link_four', models.CharField(max_length=300)),
                ('link_five', models.CharField(max_length=300)),
                ('link_si', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Python',
            },
        ),
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=300)),
                ('link_two', models.CharField(max_length=300)),
                ('link_three', models.CharField(max_length=300)),
                ('link_four', models.CharField(max_length=300)),
                ('link_five', models.CharField(max_length=300)),
                ('link_six', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Random',
            },
        ),
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=300)),
                ('link_two', models.CharField(max_length=300)),
                ('link_three', models.CharField(max_length=300)),
                ('link_four', models.CharField(max_length=300)),
                ('link_five', models.CharField(max_length=300)),
                ('link_six', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'React',
            },
        ),
        migrations.CreateModel(
            name='TypeScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=300)),
                ('link_two', models.CharField(max_length=300)),
                ('link_three', models.CharField(max_length=300)),
                ('link_four', models.CharField(max_length=300)),
                ('link_five', models.CharField(max_length=300)),
                ('link_six', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'TypeScript',
            },
        ),
        migrations.CreateModel(
            name='Html',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('body_one', models.TextField(blank=True, null=True)),
                ('body_two', models.TextField(blank=True, null=True)),
                ('body_three', models.TextField(blank=True, null=True)),
                ('body_four', models.TextField(blank=True, null=True)),
                ('link', models.CharField(max_length=300)),
                ('link_two', models.CharField(max_length=300)),
                ('link_three', models.CharField(max_length=300)),
                ('link_four', models.CharField(max_length=300)),
                ('link_five', models.CharField(max_length=300)),
                ('link_six', models.CharField(max_length=300)),
                ('like_num', models.IntegerField(default=0)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Html',
            },
        ),
    ]
