# Generated by Django 4.0.4 on 2023-11-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_newsletter_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='verification_code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
