# Generated by Django 4.0.4 on 2023-11-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_subscriber_is_verified_subscriber_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='verification_code',
        ),
    ]
