# Generated by Django 4.0.4 on 2023-11-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_subscriber_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='token',
            field=models.CharField(default=122, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
