# Generated by Django 4.0.4 on 2023-11-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_visits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visits',
            options={'verbose_name_plural': 'Visits'},
        ),
        migrations.RenameField(
            model_name='python',
            old_name='link_si',
            new_name='link_six',
        ),
        migrations.AddField(
            model_name='bootstrap',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bootstrap',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='css',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='css',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='django',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='django',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='html',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='javascript',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='javascript',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ml',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ml',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mysql',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mysql',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='python',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='python',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='random',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='random',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='react',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='react',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='typescript',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='typescript',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
