# Generated by Django 4.0.4 on 2023-11-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_visits_options_rename_link_si_python_link_six_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap',
            name='discount',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='css',
            name='discount',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='django',
            name='discount',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='html',
            name='discount',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='javascript',
            name='discount',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='ml',
            name='discount',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='mysql',
            name='discount',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='python',
            name='discount',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='random',
            name='discount',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='react',
            name='discount',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='typescript',
            name='discount',
            field=models.FloatField(default=0.35),
        ),
    ]
