# Generated by Django 4.0.4 on 2023-11-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_bootstrap_discount_css_discount_django_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstrap',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='css',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='django',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='html',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='javascript',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ml',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mysql',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='python',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='random',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='react',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='typescript',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
